### ISSUE TITLE
你好，可以完善下README 吗

### ISSUE THREAD

**Issue by kawa23** [xuhaiming1996/Bert2Transformer#2]
你好，请问该项目的效果可以在README那里展示下吗？以及如何 train 和 test 以及怎么改成自己的数据来 trian 和 test呢？可以在README那里完善下吗，谢谢。

**Comment by xuhaiming1996** [comment]
不好意思，我最近在实习，没有太多的时间。后面我会系统的写出来。欢迎一起学习

**Comment by xuhaiming1996** [comment]
你好，我已经更新了readme,希望可以帮到你。最近实在很忙，后期我会好好的整理一下

**Comment by kawa23** [comment]
感谢
