### ISSUE TITLE
BERT做生成任务的弊端

### ISSUE THREAD

**Issue by aguang1201** [xuhaiming1996/Bert2Transformer#3]
Bert这种DAE模式，在生成类NLP任务中，面临训练过程和应用过程不一致的问题，导致生成类的NLP任务到目前为止都做不太好

**Comment by xuhaiming1996** [comment]
虽然xlnet这样说，但是我认为bert最大的缺点是由于其双向性是使其不能作为解码器用于单向生成。但是我觉得它作为编码器用于提取特征还是可以的。相比xlnet，它有中文的模型

**Comment by aguang1201** [comment]
确实用BERT做为提取词向量的上游任务是很好的，归功于BERT可以参考输入句子的双向上下文。bert是transformer的encoder结构，作为encoder可以双向，但decoder不行，所以不能作为decoder。bert的缺点是上游任务训练和下游任务微调的不匹配，而自回归语言模型是没有这个问题的。但确实如你所说xlnet作为新人，还没有中文模型。
